version: '3'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend/alcahol_consumption
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myprojectuser:password@db:5432/myprojectdb
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
